### ISSUE TITLE
Change: Blank flag to be different from non-blank

### ISSUE THREAD

**Issue by winterhotlatte** [cpuabuse/node-cross-cat#3]
## Description

Currently, `-b` and `n` flags behave the same.

## Goals

- [x] Fix blank file
- [x] Verify the logic of how the functions are called when flags are set
- [x] Test the differences in actual command line calls
- [x] Rename the non-blank unit test to blank
- [x] Create unit tests for the blank

**Comment by winterhotlatte** [comment]
0383e91dd207bfb44522a80da6f6e0082b56421c

**Comment by yanocv** [comment]
Resolved.
