### ISSUE TITLE
Add: System test for the command line

### ISSUE THREAD

**Issue by winterhotlatte** [cpuabuse/node-cross-cat#5]
## Description

The system tests need to exist.

There should be several tests that test the most typical scenarios of usage, and some potential edge cases.

## Goals

- [x] File and folder structure
- [x] Plan tests
- [x] Create test data
- [x] Create expected data
- [x] Write tests

**Comment by winterhotlatte** [comment]
b4be3dcbe4713116ed2081deef97d90e071b5e57

**Comment by winterhotlatte** [comment]
eea6d1e3f1fd3d281060131e5e764a07c60dc785

**Comment by Gabriele-Gentile** [comment]
I think this is finished now. @winterhotlatte to check

**Comment by winterhotlatte** [comment]
Resolved.
